tasks:
  # Build directory
  - name: build-dir
    description: Create build directory
    actions:
      - cmd: mkdir build -p

  - name: k3d-bundle
    description: Create the UDS bundle for k3d with Core, Gitlab and its dependencies
    actions:
      - cmd: uds create bundles/k3d-core-gitlab --confirm --no-progress --architecture=${ARCH}
      - cmd: mv bundles/k3d-core-gitlab/uds-bundle-* ./build

  - name: rke2-bundle
    description: Create the UDS bundle for RKE2 with Core
    actions:
      - cmd: uds create bundles/rke2-core --confirm --no-progress --architecture=${ARCH}
      - cmd: mv bundles/rke2-core/uds-bundle-* ./build

  - name: local-path-provisioner
    description: Create local path provisioner package
    actions:
      - cmd: zarf package create src/local-path-provisioner/ --confirm --no-progress --architecture=${ARCH} --skip-sbom --output ./build

  - name: gitlab-dependency-package
    description: Create the Minio, PostgreSQL, and Redis Dependency Zarf Packages
    actions:
      - cmd: zarf package create src/dev-secrets/ --confirm --no-progress --architecture=${ARCH} --skip-sbom --output ./build

  - name: dns-updates
    description: Package to update dns updates
    actions:
      - cmd: zarf package create src/dns-updates/ --confirm --no-progress --architecture=${ARCH} --skip-sbom --output ./build
