tasks:
  # Build directory
  - name: build-dir
    description: Create build directory
    actions:
      - cmd: mkdir build -p

  - name: k3d-bundle
    description: Create the UDS bundle for k3d with Core, Gitlab and its dependencies
    actions:
      - cmd: uds create bundles/k3d-core-gitlab --confirm --no-progress --architecture=${ARCH}
      - cmd: mv bundles/k3d-core-gitlab/uds-bundle-* ./build

  - name: init-bundle
    description: Create the UDS bundle for init
    actions:
      - cmd: uds create bundles/rke2/init/ --confirm --no-progress --architecture=${ARCH}
      - cmd: mv bundles/rke2/init/uds-bundle-* ./build

  - name: uds-core-bundle
    description: Create the UDS bundle for uds-core
    actions:
      - cmd: uds create bundles/rke2/uds-core/ --confirm --no-progress --architecture=${ARCH}
      - cmd: mv bundles/rke2/uds-core/uds-bundle-* ./build

  - name: lfai-bundle
    description: Create LeapfrogAI bundle
    actions:
      - cmd: uds create bundles/rke2/lfai --confirm --no-progress --architecture=${ARCH}
      - cmd: mv bundles/rke2/lfai/uds-bundle-* ./build

  - name: swf-bundle
    description: Create SWF bundle
    actions:
      - cmd: uds create bundles/rke2/swf --confirm --no-progress --architecture=${ARCH}
      - cmd: mv bundles/rke2/swf/uds-bundle-* ./build

  - name: local-path-provisioner-package
    description: Create local path provisioner package
    actions:
      - cmd: uds zarf package create src/local-path-provisioner/ --confirm --no-progress --architecture=${ARCH} --skip-sbom --output ./build

  - name: gitlab-dependency-package
    description: Create the Minio, PostgreSQL, and Redis Dependency Zarf Packages
    actions:
      - cmd: uds zarf package create src/dev-secrets/ --confirm --no-progress --architecture=${ARCH} --skip-sbom --output ./build

  - name: dns-updates-package
    description: Package to update dns updates
    actions:
      - cmd: uds zarf package create src/dns-updates/ --confirm --no-progress --architecture=${ARCH} --skip-sbom --output ./build
