tasks:
  - name: my-bundle
    actions:
      - description: Deploy the bundle
        cmd: UDS_CONFIG=bundles/uds-config.yaml uds deploy bundles/uds-bundle-nucs-n-crannies-demo-${ARCH}-*.tar.zst --confirm --no-progress
