options:
  log_level: info
variables:
  core:
    ADMIN_TLS_CERT: |
      replace-me-with-base64-admin-cert
    ADMIN_TLS_KEY: |
      replace-me-with-base64-admin-key
    TENANT_TLS_CERT: |
      replace-me-with-base64-tenant-cert
    TENANT_TLS_KEY: |
      replace-me-with-base64-tenant-key
